---
title: "Lesson 2: R Basics for PMx"
output: rmarkdown::html_vignette
resource_files:
  - img/certara_university.jpg
  - img/certara_circle.jpg
vignette: >
  %\VignetteIndexEntry{Lesson 2: R Basics for PMx}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

## Lesson 2: R Basics for PMx

---

<div style = 'display: inline-block;'>
<center>
<a class = "registration-button" href="https://certara.zoom.us/rec/play/sEQPJ7fm8igZxLWXN1sdmt4NvxbdjXY80yaBss1yD_Z2FWpYRQpFF1MPP6KGT6epDSdRTAe-ioJHV8PJ.1VNwSfpVC1PI9bgB?continueMode=true&_x_zm_rtaid=JmDvpGG5SNC180yCXV5iWw.1654008474920.59c70952bf6f2a87a5d4d3af90b75b3d&_x_zm_rhtaid=487" target="_blank">Watch Lesson 2 Recording (Part 1)</a>
</center>
</div>

<div style = 'display: inline-block;'>
<center>
<a class = "registration-button" href="https://certara.zoom.us/rec/share/5E-MolTS1mb_61zVXO6jVYU-f68BDRqTpslTjD-9VBhPKo8ApA-_vt-Ir2FFvH2H.fq79HFKcfJeZk2kf?startTime=1654696478000" target="_blank">Watch Lesson 2 Recording (Part 2)</a>
</center>
</div>

---

Certara.R School Lesson 2 will demonstrate common R functionality needed to perform pharmacometric workflows. For example, how to import and merge data, create new columns, generate descriptive summary statistics and perform  Exploratory Data Analysis (EDA). In addition, best practices for data structure of datasets to work with RsNLME will be discussed.

<a href="https://github.com/certara/R-Certara/tree/master/inst/Certara_R_School/Lesson_2" target="_blank"> Click here</a> to access files used in Lesson 2. <a href="https://certara-training.s3.amazonaws.com/Certara.R+School/Lesson+2/Certara+R+School+Lesson+2.pdf" target="_blank"> Click here</a> to view Lesson 2 slides.

---

In the webinar we will cover the following topics:

* PK data overview
    * Recap importing/exporting different file types e.g., `csv`, `xls`, `txt`
    * [`RsNLME`](https://certara.github.io/R-RsNLME/) data structure
* Create RsNLME dataset from SDTM:
  - Data manipulation with [`dplyr`](https://dplyr.tidyverse.org/)
* Descriptive Statistics
  - Mean concentration by time
  - Demography summary
* Introduction to Exploratory Data Analysis (EDA) with [`ggplot2`](https://ggplot2.tidyverse.org/)
  - Concentration time by subject
  - Mean concentration-time by dose group
* Best practices for writing and documenting R scripts

---

<center>
<a class = "registration-button" href="https://certara.zoom.us/webinar/register/WN_jKSzJxD5SKGjqXM5WbRkHw" target="_blank">Register for Upcoming Webinar</a>
</center>

---
