# Tests for write_mcp_config(): JSON merge/idempotency and Codex snippet.

test_that("cursor project config is written and merges idempotently", {
  proj <- file.path(tempdir(), paste0("mcpcfg_", as.integer(Sys.time())))
  dir.create(proj, showWarnings = FALSE, recursive = TRUE)

  # Pre-seed an unrelated server to prove we merge, not overwrite.
  cfg_path <- file.path(proj, ".cursor", "mcp.json")
  dir.create(dirname(cfg_path), recursive = TRUE, showWarnings = FALSE)
  jsonlite::write_json(list(mcpServers = list(browsermcp = list(command = "x"))),
                       cfg_path, auto_unbox = TRUE)

  write_mcp_config(client = "cursor", scope = "project", project_dir = proj)
  cfg <- jsonlite::read_json(cfg_path)
  expect_true(!is.null(cfg$mcpServers$browsermcp))
  expect_true(!is.null(cfg$mcpServers[["certara-r"]]))
  expect_match(cfg$mcpServers[["certara-r"]]$command, "Rscript")
  expect_identical(cfg$mcpServers[["certara-r"]]$type, "stdio")
  launch <- cfg$mcpServers[["certara-r"]]$args[[2]]
  expect_match(launch, "server_name = 'certara-r'")

  rule_path <- file.path(proj, ".cursor", "rules", "certara-mcp-usage.mdc")
  expect_true(file.exists(rule_path))
  rule_txt <- paste(readLines(rule_path, warn = FALSE), collapse = "\n")
  expect_match(rule_txt, "user-certara-r")
  expect_match(rule_txt, "auto-generated by Certara.R::write_mcp_config")

  perm_path <- file.path(proj, ".cursor", "permissions.json")
  expect_true(file.exists(perm_path))
  perms <- jsonlite::read_json(perm_path)
  expect_identical(unlist(perms$mcpAllowlist, use.names = FALSE), "certara-r:*")

  # Idempotent: second write does not duplicate / change server count.
  write_mcp_config(client = "cursor", scope = "project", project_dir = proj)
  cfg2 <- jsonlite::read_json(cfg_path)
  expect_length(cfg2$mcpServers, 2)
})

test_that("a bare call targets only one client and scope", {
  proj <- file.path(tempdir(), paste0("mcpcfg_default_", as.integer(Sys.time())))
  dir.create(proj, showWarnings = FALSE, recursive = TRUE)

  acts <- suppressMessages(write_mcp_config(project_dir = proj))

  clients <- vapply(acts, function(a) a$client %||% NA_character_, character(1))
  expect_identical(unique(clients), "cursor")
  # Only the project-scope cursor file is written; no claude-code/codex action.
  expect_true(file.exists(file.path(proj, ".cursor", "mcp.json")))
  expect_false(file.exists(file.path(proj, ".mcp.json")))
})

test_that("remove_mcp_config drops our server but preserves others", {
  proj <- file.path(tempdir(), paste0("mcpcfg_rm_", as.integer(Sys.time())))
  dir.create(proj, showWarnings = FALSE, recursive = TRUE)
  cfg_path <- file.path(proj, ".cursor", "mcp.json")
  dir.create(dirname(cfg_path), recursive = TRUE, showWarnings = FALSE)
  jsonlite::write_json(list(mcpServers = list(browsermcp = list(command = "x"))),
                       cfg_path, auto_unbox = TRUE)

  write_mcp_config(client = "cursor", scope = "project", project_dir = proj)
  expect_true(!is.null(jsonlite::read_json(cfg_path)$mcpServers[["certara-r"]]))

  rule_path <- file.path(proj, ".cursor", "rules", "certara-mcp-usage.mdc")
  expect_true(file.exists(rule_path))

  acts <- remove_mcp_config(client = "cursor", scope = "project",
                            project_dir = proj)
  cfg <- jsonlite::read_json(cfg_path)
  expect_null(cfg$mcpServers[["certara-r"]])
  expect_true(!is.null(cfg$mcpServers$browsermcp))
  expect_true(acts[[1]]$removed)
  expect_true(acts[[1]]$rule_removed)
  expect_false(file.exists(rule_path))
  expect_true(acts[[1]]$permissions_removed)
  expect_false(file.exists(file.path(proj, ".cursor", "permissions.json")))

  # Removing again is a no-op that reports nothing was present.
  acts2 <- remove_mcp_config(client = "cursor", scope = "project",
                             project_dir = proj)
  expect_false(acts2[[1]]$removed)
})

test_that("codex writes user config and emits a command + TOML snippet", {
  home <- tempfile("codexhome_")
  dir.create(home)
  withr::with_envvar(c(USERPROFILE = home, HOME = home), {
    acts <- suppressMessages(
      write_mcp_config(client = "codex", scope = "project",
                       project_dir = tempdir())
    )
  })
  codex <- Filter(function(a) identical(a$client, "codex"), acts)[[1]]
  expect_match(codex$command, "codex mcp add")
  expect_match(codex$toml, "mcp_servers.certara-r")
  expect_true(file.exists(file.path(home, ".codex", "config.toml")))
  expect_true(file.exists(file.path(home, ".codex", "AGENTS.md")))
  txt <- readLines(file.path(home, ".codex", "config.toml"), warn = FALSE)
  expect_true(any(grepl("tool_timeout_sec = 900", txt, fixed = TRUE)))
  # No tool providers are installed in the host test env, so no provider marks a
  # tool gated -> no blanket approve-all and no per-tool prompt tables.
  expect_false(any(grepl('default_tools_approval_mode = "approve"', txt, fixed = TRUE)))
  expect_false(any(grepl("[mcp_servers.certara-r.tools.", txt, fixed = TRUE)))
  agents <- readLines(file.path(home, ".codex", "AGENTS.md"), warn = FALSE)
  expect_true(any(grepl("Rscript is available", agents, fixed = TRUE)))
})

test_that("codex replaces an unmanaged server block", {
  home <- tempfile("codexhome_unmanaged_")
  cfg_dir <- file.path(home, ".codex")
  dir.create(cfg_dir, recursive = TRUE)
  cfg_path <- file.path(cfg_dir, "config.toml")
  writeLines(c(
    'model = "gpt-5"',
    "",
    "[mcp_servers.certara-r]",
    'command = "old-Rscript"',
    'args = ["-e", "old_launch()"]',
    "",
    "[mcp_servers.certara-r.tools.old_tool]",
    'approval_mode = "approve"',
    "",
    "[mcp_servers.other]",
    'command = "keep-me"',
    "",
    "[projects.'c:\\\\work']",
    'trust_level = "trusted"'
  ), cfg_path)

  withr::with_envvar(c(USERPROFILE = home, HOME = home), {
    expect_no_error(
      suppressMessages(
        write_mcp_config(client = "codex", scope = "project",
                         project_dir = tempdir())
      )
    )
  })

  cfg <- readLines(cfg_path, warn = FALSE)
  expect_identical(sum(grepl("^\\[mcp_servers\\.certara-r\\]$", cfg)), 1L)
  expect_true(any(grepl("# BEGIN certara-r MCP config", cfg, fixed = TRUE)))
  expect_true(any(grepl("tool_timeout_sec = 900", cfg, fixed = TRUE)))
  expect_false(any(grepl('default_tools_approval_mode = "approve"', cfg, fixed = TRUE)))
  expect_false(any(grepl("old-Rscript", cfg, fixed = TRUE)))
  expect_false(any(grepl("old_tool", cfg, fixed = TRUE)))
  expect_true(any(grepl("[mcp_servers.other]", cfg, fixed = TRUE)))
  expect_true(any(grepl("[projects.'c:\\\\work']", cfg, fixed = TRUE)))
})

test_that("user-scope cursor path resolves to the client's profile root", {
  # On Windows the client reads %USERPROFILE%\.cursor, not R's "~" (Documents).
  skip_on_os(c("mac", "linux", "solaris"))
  withr::with_envvar(c(USERPROFILE = "C:/Users/tester"), {
    p <- .cursor_config_path("user", project_dir = ".")
    expect_identical(normalizePath(dirname(dirname(p)), mustWork = FALSE),
                     normalizePath("C:/Users/tester", mustWork = FALSE))
  })
})

test_that("user-scope cursor writes permissions.json under profile .cursor", {
  fake_home <- file.path(tempdir(), paste0("fakehome_", as.integer(Sys.time())))
  dir.create(fake_home, showWarnings = FALSE, recursive = TRUE)
  env <- if (.Platform$OS.type == "windows") {
    c(USERPROFILE = fake_home)
  } else {
    c(HOME = fake_home)
  }
  withr::with_envvar(env, {
    write_mcp_config(client = "cursor", scope = "user")
    perm_path <- file.path(fake_home, ".cursor", "permissions.json")
    expect_true(file.exists(perm_path))
    expect_identical(
      unlist(jsonlite::read_json(perm_path)$mcpAllowlist, use.names = FALSE),
      "certara-r:*"
    )
    acts <- remove_mcp_config(client = "cursor", scope = "user")
    expect_true(acts[[1]]$permissions_removed)
    expect_false(file.exists(perm_path))
  })
})

test_that("claude-code user scope passes -s user to the CLI", {
  # Isolate the profile root so the user-scope guidance/settings writes do not
  # touch the real home directory.
  fake_home <- file.path(tempdir(), paste0("cchome_user_", as.integer(Sys.time())))
  dir.create(fake_home, showWarnings = FALSE, recursive = TRUE)
  env <- if (.Platform$OS.type == "windows") {
    c(USERPROFILE = fake_home, HOME = fake_home)
  } else {
    c(HOME = fake_home)
  }
  withr::with_envvar(env, {
    add <- suppressMessages(
      write_mcp_config(client = "claude-code", scope = "user")
    )
    cc <- Filter(function(a) identical(a$client, "claude-code"), add)[[1]]
    expect_match(cc$command, "mcp add -s user certara-r")

    rm <- suppressMessages(
      remove_mcp_config(client = "claude-code", scope = "user")
    )
    cc_rm <- Filter(function(a) identical(a$client, "claude-code"), rm)[[1]]
    expect_match(cc_rm$command, "mcp remove -s user certara-r")
  })
})

test_that("claude-code local scope passes -s local to the CLI", {
  proj <- file.path(tempdir(), paste0("mcpcfg_cclocal_", as.integer(Sys.time())))
  dir.create(proj, showWarnings = FALSE, recursive = TRUE)
  add <- suppressMessages(
    write_mcp_config(client = "claude-code", scope = "local", project_dir = proj)
  )
  cc <- Filter(function(a) identical(a$client, "claude-code"), add)[[1]]
  expect_identical(cc$scope, "local")
  expect_match(cc$command, "mcp add -s local certara-r")

  rm <- suppressMessages(
    remove_mcp_config(client = "claude-code", scope = "local", project_dir = proj)
  )
  cc_rm <- Filter(function(a) identical(a$client, "claude-code"), rm)[[1]]
  expect_match(cc_rm$command, "mcp remove -s local certara-r")
})

test_that("claude-code installs and removes a CLAUDE.md-imported guidance doc", {
  proj <- file.path(tempdir(), paste0("mcpcfg_ccguide_", as.integer(Sys.time())))
  dir.create(proj, showWarnings = FALSE, recursive = TRUE)
  # Pre-seed CLAUDE.md to prove the managed block is appended, not clobbered.
  claude_md <- file.path(proj, "CLAUDE.md")
  writeLines(c("# Project notes", "", "Keep me."), claude_md)

  acts <- suppressMessages(
    write_mcp_config(client = "claude-code", scope = "project", project_dir = proj)
  )
  cc <- Filter(function(a) identical(a$client, "claude-code"), acts)[[1]]

  doc <- file.path(proj, ".claude", "certara-mcp-usage.md")
  expect_true(file.exists(doc))
  doc_txt <- paste(readLines(doc, warn = FALSE), collapse = "\n")
  expect_match(doc_txt, "certara_mcp_capabilities")        # session-start nudge
  expect_match(doc_txt, "auto-generated by Certara.R::write_mcp_config")
  expect_identical(cc$guidance_written$doc, doc)

  md <- readLines(claude_md, warn = FALSE)
  expect_true(any(grepl("@.claude/certara-mcp-usage.md", md, fixed = TRUE)))
  expect_true(any(grepl("Keep me.", md, fixed = TRUE)))     # user content kept

  # Idempotent: a second write must not duplicate the import block.
  suppressMessages(
    write_mcp_config(client = "claude-code", scope = "project", project_dir = proj)
  )
  md2 <- readLines(claude_md, warn = FALSE)
  expect_length(grep("@.claude/certara-mcp-usage.md", md2, fixed = TRUE), 1)

  # Removal: doc deleted, block stripped, user content preserved.
  rm <- suppressMessages(
    remove_mcp_config(client = "claude-code", scope = "project", project_dir = proj)
  )
  cc_rm <- Filter(function(a) identical(a$client, "claude-code"), rm)[[1]]
  expect_true(isTRUE(cc_rm$guidance_removed))
  expect_false(file.exists(doc))
  md3 <- readLines(claude_md, warn = FALSE)
  expect_false(any(grepl("certara-mcp-usage.md", md3, fixed = TRUE)))
  expect_true(any(grepl("Keep me.", md3, fixed = TRUE)))
})

test_that("claude-code guidance creates CLAUDE.md when absent and deletes it on removal", {
  proj <- file.path(tempdir(), paste0("mcpcfg_ccguide2_", as.integer(Sys.time())))
  dir.create(proj, showWarnings = FALSE, recursive = TRUE)

  suppressMessages(
    write_mcp_config(client = "claude-code", scope = "project", project_dir = proj)
  )
  claude_md <- file.path(proj, "CLAUDE.md")
  expect_true(file.exists(claude_md))

  suppressMessages(
    remove_mcp_config(client = "claude-code", scope = "project", project_dir = proj)
  )
  # CLAUDE.md held only our block, so removal deletes it.
  expect_false(file.exists(claude_md))
})

test_that("cursor skips 'local' scope with a warning, leaving files untouched", {
  proj <- file.path(tempdir(), paste0("mcpcfg_curlocal_", as.integer(Sys.time())))
  dir.create(proj, showWarnings = FALSE, recursive = TRUE)

  expect_warning(
    write_mcp_config(client = "cursor", scope = "local", project_dir = proj),
    "no 'local' scope"
  )
  # Nothing written for the unsupported scope.
  expect_false(file.exists(file.path(proj, ".cursor", "mcp.json")))

  # 'project' scope still behaves exactly as before alongside a skipped 'local'.
  suppressWarnings(
    write_mcp_config(client = "cursor", scope = c("project", "local"),
                     project_dir = proj)
  )
  cfg <- jsonlite::read_json(file.path(proj, ".cursor", "mcp.json"))
  expect_true(!is.null(cfg$mcpServers[["certara-r"]]))
})

test_that("run = TRUE falls back to printing when the CLI is absent", {
  rec <- suppressMessages(
    .cli_command(
      "Codex (user scope)",
      "certara-rsnlme-definitely-missing-codex-cli",
      c("mcp", "remove", "certara-r"),
      run = TRUE
    )
  )
  expect_false(isTRUE(rec$ran))
  expect_match(rec$command, "certara-rsnlme-definitely-missing-codex-cli mcp remove")
})

test_that("launch expression encodes btw groups and session flag", {
  expr <- .mcp_launch_expr(c("docs", "pkg"), FALSE, "certara-r")
  expect_match(expr, "launch_certara_mcp")
  expect_match(expr, "c\\('docs', 'pkg'\\)")
  expect_match(expr, "session_tools = FALSE")
  expect_match(expr, "server_name = 'certara-r'")
  # Default watch budget is baked into the launch command.
  expect_match(expr, "job_watch_wait_seconds = 45")
})

test_that("launch expression carries an explicit watch budget", {
  expr <- .mcp_launch_expr(c("docs"), FALSE, "certara-r",
                           job_watch_wait_seconds = 600)
  expect_match(expr, "job_watch_wait_seconds = 600")
})

test_that("per-client watch budgets: cursor 45, claude/codex 600", {
  proj <- file.path(tempdir(), paste0("mcpcfg_watch_", as.integer(Sys.time())))
  dir.create(proj, showWarnings = FALSE, recursive = TRUE)
  home <- tempfile("watchhome_")
  dir.create(home)

  withr::with_envvar(c(USERPROFILE = home, HOME = home), {
    suppressMessages(write_mcp_config(
      client = c("cursor", "claude-code", "codex"),
      scope = "project", project_dir = proj))
  })

  cursor_launch <- jsonlite::read_json(
    file.path(proj, ".cursor", "mcp.json"))$mcpServers[["certara-r"]]$args[[2]]
  expect_match(cursor_launch, "job_watch_wait_seconds = 45")

  claude_entry <- jsonlite::read_json(
    file.path(proj, ".mcp.json"))$mcpServers[["certara-r"]]
  expect_match(claude_entry$args[[2]], "job_watch_wait_seconds = 600")
  # Per-server tool-call timeout (ms) = budget + 60s margin.
  expect_identical(claude_entry$timeout, 660000L)

  codex_cfg <- readLines(file.path(home, ".codex", "config.toml"), warn = FALSE)
  expect_true(any(grepl("job_watch_wait_seconds = 600", codex_cfg, fixed = TRUE)))
  expect_true(any(grepl("tool_timeout_sec = 900", codex_cfg, fixed = TRUE)))
})

test_that("explicit job_watch_wait_seconds overrides every client", {
  proj <- file.path(tempdir(), paste0("mcpcfg_watchov_", as.integer(Sys.time())))
  dir.create(proj, showWarnings = FALSE, recursive = TRUE)
  home <- tempfile("watchovhome_")
  dir.create(home)

  withr::with_envvar(c(USERPROFILE = home, HOME = home), {
    suppressMessages(write_mcp_config(
      client = c("cursor", "claude-code", "codex"),
      scope = "project", project_dir = proj,
      job_watch_wait_seconds = 120))
  })

  cursor_launch <- jsonlite::read_json(
    file.path(proj, ".cursor", "mcp.json"))$mcpServers[["certara-r"]]$args[[2]]
  expect_match(cursor_launch, "job_watch_wait_seconds = 120")

  claude_entry <- jsonlite::read_json(
    file.path(proj, ".mcp.json"))$mcpServers[["certara-r"]]
  expect_match(claude_entry$args[[2]], "job_watch_wait_seconds = 120")
  expect_identical(claude_entry$timeout, 180000L)

  codex_cfg <- readLines(file.path(home, ".codex", "config.toml"), warn = FALSE)
  expect_true(any(grepl("job_watch_wait_seconds = 120", codex_cfg, fixed = TRUE)))
})

test_that("tool_allowlist = FALSE skips cursor permissions.json", {
  proj <- file.path(tempdir(), paste0("mcpcfg_noallow_", as.integer(Sys.time())))
  dir.create(proj, showWarnings = FALSE, recursive = TRUE)

  write_mcp_config(client = "cursor", scope = "project", project_dir = proj,
                   tool_allowlist = FALSE)
  expect_false(file.exists(file.path(proj, ".cursor", "permissions.json")))
})

test_that("tool_allowlist writes claude-code settings allowlist per scope", {
  proj <- file.path(tempdir(), paste0("mcpcfg_ccallow_", as.integer(Sys.time())))
  dir.create(proj, showWarnings = FALSE, recursive = TRUE)

  # project scope -> .claude/settings.json (and the server in .mcp.json).
  suppressMessages(
    write_mcp_config(client = "claude-code", scope = "project", project_dir = proj)
  )
  expect_true(!is.null(
    jsonlite::read_json(file.path(proj, ".mcp.json"))$mcpServers[["certara-r"]]
  ))
  proj_set <- jsonlite::read_json(file.path(proj, ".claude", "settings.json"))
  expect_true("mcp__certara-r" %in%
                unlist(proj_set$permissions$allow, use.names = FALSE))

  # local scope -> .claude/settings.local.json.
  suppressMessages(
    write_mcp_config(client = "claude-code", scope = "local", project_dir = proj)
  )
  local_set <- jsonlite::read_json(file.path(proj, ".claude", "settings.local.json"))
  expect_true("mcp__certara-r" %in%
                unlist(local_set$permissions$allow, use.names = FALSE))
})

test_that("claude-code allowlist merges with and removes from existing settings", {
  proj <- file.path(tempdir(), paste0("mcpcfg_ccmerge_", as.integer(Sys.time())))
  dir.create(file.path(proj, ".claude"), showWarnings = FALSE, recursive = TRUE)
  set_path <- file.path(proj, ".claude", "settings.json")
  # Pre-seed unrelated settings to prove we merge, not clobber.
  jsonlite::write_json(
    list(model = "opus", permissions = list(allow = list("Bash(ls:*)"))),
    set_path, auto_unbox = TRUE
  )

  suppressMessages(
    write_mcp_config(client = "claude-code", scope = "project", project_dir = proj)
  )
  set <- jsonlite::read_json(set_path)
  allow <- unlist(set$permissions$allow, use.names = FALSE)
  expect_true(all(c("Bash(ls:*)", "mcp__certara-r") %in% allow))
  expect_identical(set$model, "opus")

  acts <- suppressMessages(
    remove_mcp_config(client = "claude-code", scope = "project", project_dir = proj)
  )
  cc <- Filter(function(a) identical(a$client, "claude-code"), acts)[[1]]
  expect_true(isTRUE(cc$permissions_removed))
  set2 <- jsonlite::read_json(set_path)
  allow2 <- unlist(set2$permissions$allow, use.names = FALSE)
  expect_false("mcp__certara-r" %in% allow2)        # ours gone
  expect_true("Bash(ls:*)" %in% allow2)             # unrelated preserved
  expect_identical(set2$model, "opus")              # other keys preserved
})

test_that("tool_allowlist = FALSE skips the claude-code settings allowlist", {
  proj <- file.path(tempdir(), paste0("mcpcfg_ccnoallow_", as.integer(Sys.time())))
  dir.create(proj, showWarnings = FALSE, recursive = TRUE)

  suppressMessages(
    write_mcp_config(client = "claude-code", scope = "project", project_dir = proj,
                     tool_allowlist = FALSE)
  )
  expect_false(file.exists(file.path(proj, ".claude", "settings.json")))
})

test_that("codex writes MCP approval settings when tool_allowlist is TRUE", {
  home <- tempfile("codexhome_allow_")
  dir.create(home)
  expect_message(
    withr::with_envvar(c(USERPROFILE = home, HOME = home), {
      suppressWarnings(
        write_mcp_config(client = "codex", scope = "project",
                         project_dir = tempdir())
      )
    }),
    "MCP tool approvals"
  )
  cfg <- readLines(file.path(home, ".codex", "config.toml"), warn = FALSE)
  expect_true(any(grepl("tool_timeout_sec = 900", cfg, fixed = TRUE)))
  # Without an installed provider declaring a gated tool, Codex prompts for all.
  expect_false(any(grepl('default_tools_approval_mode = "approve"', cfg, fixed = TRUE)))
  expect_false(any(grepl('approval_mode = "prompt"', cfg, fixed = TRUE)))
})

test_that("agent is an alias for client", {
  home <- tempfile("codexhome_agent_")
  dir.create(home)
  withr::with_envvar(c(USERPROFILE = home, HOME = home), {
    acts <- suppressMessages(write_mcp_config(agent = "codex"))
  })
  codex <- Filter(function(a) identical(a$client, "codex"), acts)[[1]]
  expect_true(file.exists(codex$written))
  expect_error(
    write_mcp_config(client = "cursor", agent = "codex"),
    "Use either 'client' or 'agent'"
  )
})

test_that("permissions.json merges with existing entries", {
  proj <- file.path(tempdir(), paste0("mcpcfg_permmerge_", as.integer(Sys.time())))
  dir.create(proj, showWarnings = FALSE, recursive = TRUE)
  perm_path <- file.path(proj, ".cursor", "permissions.json")
  dir.create(dirname(perm_path), recursive = TRUE, showWarnings = FALSE)
  jsonlite::write_json(
    list(mcpAllowlist = list("github:*")),
    perm_path, auto_unbox = TRUE
  )

  write_mcp_config(client = "cursor", scope = "project", project_dir = proj)
  allow <- unlist(jsonlite::read_json(perm_path)$mcpAllowlist, use.names = FALSE)
  expect_true("github:*" %in% allow)
  expect_true("certara-r:*" %in% allow)
  expect_length(allow, 2)
})

test_that("custom server_name propagates to launch expr and cursor rule", {
  proj <- file.path(tempdir(), paste0("mcpcfg_custom_", as.integer(Sys.time())))
  dir.create(proj, showWarnings = FALSE, recursive = TRUE)

  write_mcp_config(client = "cursor", scope = "project", project_dir = proj,
                   server_name = "rsnlme-mcp")
  cfg <- jsonlite::read_json(file.path(proj, ".cursor", "mcp.json"))
  expect_match(cfg$mcpServers$`rsnlme-mcp`$args[[2]], "server_name = 'rsnlme-mcp'")

  rule_txt <- readLines(file.path(proj, ".cursor", "rules", "certara-mcp-usage.mdc"),
                        warn = FALSE)
  expect_true(any(grepl("user-rsnlme-mcp", rule_txt, fixed = TRUE)))
})

test_that("codex run = TRUE does not double-write the server table or invoke the CLI", {
  home <- tempfile("codexhome_run_")
  dir.create(home)
  withr::with_envvar(c(USERPROFILE = home, HOME = home), {
    acts <- suppressMessages(
      write_mcp_config(client = "codex", scope = "project",
                       project_dir = tempdir(), run = TRUE)
    )
  })
  codex <- Filter(function(a) identical(a$client, "codex"), acts)[[1]]
  # The file write is the configuration; the CLI is never invoked (no second
  # [mcp_servers.certara-r] table from `codex mcp add`).
  expect_false(isTRUE(codex$ran))
  cfg <- readLines(file.path(home, ".codex", "config.toml"), warn = FALSE)
  headers <- sum(grepl("^\\[mcp_servers\\.certara-r\\]$", cfg))
  expect_identical(headers, 1L)
})

test_that("remove_mcp_config strips the codex managed block and AGENTS note", {
  home <- tempfile("codexhome_rm_")
  dir.create(home)
  withr::with_envvar(c(USERPROFILE = home, HOME = home), {
    suppressMessages(write_mcp_config(client = "codex", scope = "project",
                                      project_dir = tempdir()))
    cfg_path <- file.path(home, ".codex", "config.toml")
    agents_path <- file.path(home, ".codex", "AGENTS.md")
    expect_true(any(grepl("mcp_servers.certara-r",
                          readLines(cfg_path, warn = FALSE), fixed = TRUE)))

    acts <- suppressMessages(remove_mcp_config(client = "codex",
                                               project_dir = tempdir()))
    rec <- Filter(function(a) identical(a$client, "codex"), acts)[[1]]
    expect_true(isTRUE(rec$config_removed))
    # The managed block is gone (file deleted when it held nothing else).
    leftover <- if (file.exists(cfg_path)) readLines(cfg_path, warn = FALSE) else character(0)
    expect_false(any(grepl("mcp_servers.certara-r", leftover, fixed = TRUE)))
    leftover_agents <- if (file.exists(agents_path)) {
      readLines(agents_path, warn = FALSE)
    } else {
      character(0)
    }
    expect_false(any(grepl("Certara R local R", leftover_agents, fixed = TRUE)))
  })
})

test_that("codex AGENTS note gives a platform-appropriate PATH hint", {
  home <- tempfile("codexhome_path_")
  dir.create(home)
  withr::with_envvar(c(USERPROFILE = home, HOME = home), {
    suppressMessages(write_mcp_config(client = "codex", scope = "project",
                                      project_dir = tempdir()))
  })
  agents <- readLines(file.path(home, ".codex", "AGENTS.md"), warn = FALSE)
  expect_true(any(grepl("prepend it to PATH", agents, fixed = TRUE)))
  if (.Platform$OS.type == "windows") {
    expect_true(any(grepl("$env:Path", agents, fixed = TRUE)))
  } else {
    expect_true(any(grepl("export PATH", agents, fixed = TRUE)))
  }
})

test_that(".toml_string_array escapes backslashes and quotes", {
  out <- .toml_string_array(c("C:\\Program Files\\R", "say \"hi\""))
  # A single literal backslash becomes a doubled (escaped) backslash in TOML.
  expect_match(out, "C:\\\\Program", fixed = TRUE)
  # A literal double-quote becomes \" in TOML.
  expect_match(out, "\\\"hi\\\"", fixed = TRUE)
})

# ---- Claude Desktop / Cowork ------------------------------------------------

# Point .claude_desktop_config_dir() at a temp tree (no MSIX package) per OS, so
# the merge/guidance tests run cross-platform.
desktop_env <- function(dir) {
  if (.Platform$OS.type == "windows") {
    empty <- file.path(dir, "local_empty")
    dir.create(empty, showWarnings = FALSE, recursive = TRUE)
    c(LOCALAPPDATA = empty, APPDATA = dir)
  } else {
    c(HOME = dir)
  }
}

test_that("claude-desktop writes and merges claude_desktop_config.json", {
  root <- tempfile("desktoproot_")
  dir.create(root)

  withr::with_envvar(desktop_env(root), {
    cfg_path <- .claude_desktop_config_path()
    dir.create(dirname(cfg_path), showWarnings = FALSE, recursive = TRUE)
    # Pre-seed an unrelated server to prove we merge, not overwrite.
    jsonlite::write_json(list(mcpServers = list(filesystem = list(command = "x"))),
                         cfg_path, auto_unbox = TRUE)

    acts <- suppressMessages(write_mcp_config(client = "claude-desktop"))

    cfg <- jsonlite::read_json(cfg_path)
    expect_true(!is.null(cfg$mcpServers$filesystem))
    expect_true(!is.null(cfg$mcpServers[["certara-r"]]))
    expect_identical(cfg$mcpServers[["certara-r"]]$type, "stdio")
    expect_match(cfg$mcpServers[["certara-r"]]$command, "Rscript")
    # Desktop gets the long (600s) watch budget and no per-server timeout key.
    expect_match(cfg$mcpServers[["certara-r"]]$args[[2]],
                 "job_watch_wait_seconds = 600")
    expect_null(cfg$mcpServers[["certara-r"]]$timeout)

    dt <- Filter(function(a) identical(a$client, "claude-desktop"), acts)[[1]]
    expect_identical(dt$scope, "user")
    expect_identical(normalizePath(dt$written, mustWork = FALSE),
                     normalizePath(cfg_path, mustWork = FALSE))

    # Idempotent: second write keeps two servers, no duplication.
    suppressMessages(write_mcp_config(client = "claude-desktop"))
    expect_length(jsonlite::read_json(cfg_path)$mcpServers, 2)
  })
})

test_that("claude-desktop writes a manual, not-auto-loaded guidance doc", {
  root <- tempfile("desktopguide_")
  dir.create(root)

  withr::with_envvar(desktop_env(root), {
    suppressMessages(write_mcp_config(client = "claude-desktop"))
    doc <- file.path(dirname(.claude_desktop_config_path()), "certara-mcp-usage.md")
    expect_true(file.exists(doc))
    txt <- paste(readLines(doc, warn = FALSE), collapse = "\n")
    expect_match(txt, "auto-generated by Certara.R::write_mcp_config")
    expect_match(txt, "does NOT auto-load", fixed = TRUE)
    expect_match(txt, "certara_mcp_capabilities", fixed = TRUE)

    acts <- suppressMessages(remove_mcp_config(client = "claude-desktop"))
    dt <- Filter(function(a) identical(a$client, "claude-desktop"), acts)[[1]]
    expect_true(isTRUE(dt$removed))
    expect_true(isTRUE(dt$guidance_removed))
    expect_false(file.exists(doc))
    # Our server is gone (the file held only certara-r, so mcpServers is empty).
    cfg <- jsonlite::read_json(.claude_desktop_config_path())
    expect_null(cfg$mcpServers[["certara-r"]])
  })
})

test_that("claude-desktop prefers the MSIX virtualized path on Windows", {
  if (.Platform$OS.type != "windows") skip("Windows-only path resolution")
  local <- tempfile("localappdata_")
  msix <- file.path(local, "Packages", "Claude_pzs8sxrjxfjjc",
                    "LocalCache", "Roaming", "Claude")
  dir.create(msix, recursive = TRUE)

  withr::with_envvar(c(LOCALAPPDATA = local, APPDATA = file.path(local, "Roaming")), {
    expect_identical(normalizePath(.claude_desktop_config_dir(), mustWork = FALSE),
                     normalizePath(msix, mustWork = FALSE))
    expect_true(.claude_desktop_msix_active())
  })
})

test_that("claude-desktop falls back to APPDATA when no MSIX package exists", {
  if (.Platform$OS.type != "windows") skip("Windows-only path resolution")
  local <- tempfile("localappdata_empty_")
  appdata <- tempfile("appdata_")
  dir.create(local)
  dir.create(appdata)

  withr::with_envvar(c(LOCALAPPDATA = local, APPDATA = appdata), {
    expect_identical(normalizePath(.claude_desktop_config_dir(), mustWork = FALSE),
                     normalizePath(file.path(appdata, "Claude"), mustWork = FALSE))
    expect_false(.claude_desktop_msix_active())
  })
})

test_that("unknown btw_groups is rejected", {
  proj <- file.path(tempdir(), paste0("mcpcfg_btw_", as.integer(Sys.time())))
  dir.create(proj, showWarnings = FALSE, recursive = TRUE)
  expect_error(
    write_mcp_config(client = "cursor", scope = "project", project_dir = proj,
                     btw_groups = "evil_injection"),
    "Unknown btw_groups"
  )
})

test_that("valid btw_groups including pkg still writes config", {
  proj <- file.path(tempdir(), paste0("mcpcfg_btwok_", as.integer(Sys.time())))
  dir.create(proj, showWarnings = FALSE, recursive = TRUE)
  write_mcp_config(client = "cursor", scope = "project", project_dir = proj,
                   btw_groups = c("docs", "pkg"))
  launch <- jsonlite::read_json(
    file.path(proj, ".cursor", "mcp.json"))$mcpServers[["certara-r"]]$args[[2]]
  expect_match(launch, "c\\('docs', 'pkg'\\)")
})
